package cli

const defaultConfig = `# ailinter configuration
# Generated by: ailinter init

extends = "default"

[rules]
deep_nesting = { weight = 1.0, warning = 3, alert = 5 }
brain_method = { weight = 1.0, warning_lines = 70, alert_lines = 200 }
file_bloat = { weight = 1.0, warning_lines = 500, alert_lines = 2000 }
complex_conditional = { weight = 1.0, branches_warning = 2, branches_alert = 5 }
bumpy_road = { weight = 1.0, bumps_warning = 2, bump_depth = 2 }
long_parameter_list = { weight = 1.0, warning = 4, alert = 7 }
excessive_comments = { ratio = 0.3 }
global_data = { warning = 5 }
long_scope_variable = { min_lines = 50 }

[gitleaks]
extend = "default"

[mcp]
enabled_tools = ["*"]
read_only = false
`

const defaultAgentsMD = "# AGENTS.md\n\n" +
	"## Agent TL;DR\n\n" +
	"- **Code Quality is authoritative.** Treat it as the single source of truth for maintainability.\n" +
	"- **Target Code Quality 100.** This is the standard for AI-friendly code.\n" +
	"- **Safeguard all AI-touched code** before suggesting a commit — run `ailinter check` on every changed file.\n" +
	"- **If issues are found: the refactoring loop.** Call `get_refactoring_strategy()` → refactor in 3-5 steps → re-run `analyze_code` to confirm improvement. Never skip this loop.\n" +
	"- Use `ailinter check` to guide **incremental, high-impact refactorings** in 3-5 small steps.\n" +
	"- When in doubt, **call the appropriate ailinter MCP tool — don't guess.**\n" +
	"\n" +
	"---\n\n" +
	"## Common Workflow: The Refactoring Loop\n\n" +
	"Whenever you modify code, follow this loop:\n\n" +
	"```\n" +
	"1. BEFORE edit: analyze_code(file) → know the score\n" +
	"2. If score < 95 or smells found:\n" +
	"   a. get_refactoring_strategy(\"smell_name\") → exact instructions\n" +
	"   b. Refactor in 3-5 small steps\n" +
	"   c. Re-run analyze_code after each step → confirm score improves\n" +
	"3. Make your feature/bugfix change\n" +
	"4. AFTER edit: analyze_code(file) → no regression\n" +
	"5. scan_for_secrets(content) → clean\n" +
	"6. Commit\n" +
	"```\n" +
	"\n" +
	"---\n\n" +
	"## Available MCP Tools\n\n" +
	"| Tool | Purpose |\n" +
	"|------|---------|\n" +
	"| `analyze_code` | Full structural analysis + vulnerability detection: quality score (0-100), issues, severity, locations |\n" +
	"| `scan_for_secrets` | Secret detection: AWS keys, API tokens, private keys, JWT, etc. |\n" +
	"| `get_refactoring_strategy` | 🔧 NEXT STEP after analyze_code finds issues — exact refactoring steps + before/after examples for 8+ smells |\n" +
	"| `assess_file` | Quick classification: Go Ahead / Proceed with Care / Stop & Refactor |\n" +
	"\n" +
	"---\n\n" +
	"## Quality Score Reference\n\n" +
	"| Score | Label | AI Guidance |\n" +
	"|-------|-------|-------------|\n" +
	"| 95-100 | Go Ahead | Safe for AI modification |\n" +
	"| 75-94 | Proceed with Care | Use guard clauses, prefer small changes, re-check after each edit |\n" +
	"| 0-74 | Stop & Refactor | Refactor BEFORE AI modification — call get_refactoring_strategy first |\n" +
	"\n" +
	"---\n\n" +
	"## Language-Specific Thresholds (Defaults)\n\n" +
	"| Metric | Go | Python | JS/TS | Java |\n" +
	"|--------|:--:|:--:|:--:|:--:|\n" +
	"| Max nesting depth (warn) | 4 | 4 | 3 | 4 |\n" +
	"| Max cyclomatic complexity (warn) | 9 | 9 | 9 | 9 |\n" +
	"| Max function LOC (warn) | 80 | 70 | 60 | 70 |\n" +
	"| Max file LOC (warn) | 1000 | 600 | 700 | 600 |\n" +
	"| Max function arguments | 4 | 4 | 4 | 5 |\n" +
	"\n" +
	"Customize via `.ailinter.toml` in project root.\n" +
	"\n" +
	"---\n\n" +
	"## Supported Smells for get_refactoring_strategy\n\n" +
	"| Smell | What It Detects | Strategy |\n" +
	"|-------|----------------|----------|\n" +
	"| deep_nesting | Brace level > 3-4 | Guard Clauses + Extract Method |\n" +
	"| brain_method | Functions > 60-80 LOC | Extract Method decomposition |\n" +
	"| bumpy_road | Multiple deep blocks | Extract Method per bump |\n" +
	"| complex_conditional | Excessive &&/|| branches | Introduce Clause + Strategy Pattern |\n" +
	"| god_class | Too many responsibilities | Extract Class + SRP |\n" +
	"| long_parameter_list | > 4 parameters | Parameter Object pattern |\n" +
	"| primitive_obsession | Primitive-type overuse | Type Wrapper + Value Object |\n" +
	"| duplicated_code | Near-identical blocks | Extract Method + Template Method |\n" +
	"\n" +
	"---\n\n" +
	"## Attribution\n\n" +
	"Code smell definitions adapted from the [Samman Coaching Code Smells Reference](https://sammancoaching.org/reference/code_smells/index.html) by Emily Bache, licensed under CC BY-SA 4.0.\n"

const defaultVSCodeTasks = `{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "ailinter: check current file",
      "type": "shell",
      "command": "ailinter",
      "args": ["check", "--format", "problems", "${file}"],
      "problemMatcher": {
        "base": "$gcc",
        "owner": "ailinter",
        "source": "ailinter",
        "fileLocation": ["absolute"],
        "pattern": {
          "regexp": "^(.*):(\\d+):(\\d+): (error|warning): (\\S+): (.*)$",
          "file": 1,
          "line": 2,
          "column": 3,
          "severity": 4,
          "code": 5,
          "message": 6
        }
      },
      "group": "build"
    },
    {
      "label": "ailinter: check workspace",
      "type": "shell",
      "command": "ailinter",
      "args": ["check", "--format", "problems", "${workspaceFolder}"],
      "problemMatcher": {
        "base": "$gcc",
        "owner": "ailinter",
        "source": "ailinter",
        "fileLocation": ["absolute"],
        "pattern": {
          "regexp": "^(.*):(\\d+):(\\d+): (error|warning): (\\S+): (.*)$",
          "file": 1,
          "line": 2,
          "column": 3,
          "severity": 4,
          "code": 5,
          "message": 6
        }
      },
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ]
}
`
